"use client"

const netBankingCodes = [
    { name: "Airtel Payments Bank", code: 3123, tpv: "N" },
    { name: "Andhra Pragathi Grameena Bank", code: 3094, tpv: "N" },
    { name: "AU Small Finance Bank", code: 3087, tpv: "Y" },
    { name: "Axis Bank", code: 3003, tpv: "Y" },
    { name: "Axis Bank - Corporate", code: 3071, tpv: "N" },
    { name: "Bandhan Bank - Retail Banking", code: 3088, tpv: "Y" },
    { name: "Bank of Bahrain and Kuwait", code: 3095, tpv: "N" },
    { name: "Bank of Baroda - Corporate", code: 3060, tpv: "Y" },
    { name: "Bank of Baroda - Retail Banking", code: 3005, tpv: "Y" },
    { name: "Bank of India", code: 3006, tpv: "Y" },
    { name: "Bank of India - Corporate", code: 3061, tpv: "N" },
    { name: "Bank of Maharashtra", code: 3007, tpv: "Y" },
    { name: "Barclays - Corporate", code: 3080, tpv: "N" },
    { name: "Canara Bank", code: 3009, tpv: "Y" },
    { name: "Capital Small Finance Bank", code: 3098, tpv: "Y" },
    { name: "Central Bank of India", code: 3011, tpv: "Y" },
    { name: "City Union Bank", code: 3012, tpv: "Y" },
    { name: "Cosmos Bank", code: 3097, tpv: "Y" },
    { name: "CSB Bank Limited", code: 3010, tpv: "Y" },
    { name: "DBS Bank Ltd", code: 3017, tpv: "N" },
    { name: "DCB Bank - Personal", code: 3018, tpv: "N" },
    { name: "Deutsche Bank", code: 3016, tpv: "Y" },
    { name: "Dhanlakshmi Bank", code: 3019, tpv: "Y" },
    { name: "Dhanlaxmi Bank - Corporate", code: 3072, tpv: "N" },
    { name: "Equitas Small Finance Bank", code: 3076, tpv: "N" },
    { name: "ESAF Small Finance Bank", code: 3100, tpv: "N" },
    { name: "Federal Bank", code: 3020, tpv: "Y" },
    { name: "Fincare Bank", code: 3101, tpv: "N" },
    { name: "Gujarat State Co-operative Bank Limited", code: 3091, tpv: "Y" },
    { name: "HDFC Bank", code: 3021, tpv: "Y" },
    { name: "HDFC Corporate", code: 3084, tpv: "N" },
    { name: "HSBC Retail NetBanking", code: 3092, tpv: "Y" },
    { name: "ICICI Bank", code: 3022, tpv: "Y" },
    { name: "ICICI Bank - Corporate", code: 3073, tpv: "N" },
    { name: "IDBI Bank", code: 3023, tpv: "Y" },
    { name: "IDBI Bank - Corporate", code: 3124, tpv: "N" },
    { name: "IDFC FIRST Bank", code: 3024, tpv: "Y" },
    { name: "Indian Bank", code: 3026, tpv: "Y" },
    { name: "Indian Overseas Bank", code: 3027, tpv: "Y" },
    { name: "Indian Overseas Bank - Corporate", code: 3081, tpv: "N" },
    { name: "IndusInd Bank", code: 3028, tpv: "Y" },
    { name: "Jammu and Kashmir Bank", code: 3029, tpv: "Y" },
    { name: "Jana Small Finance Bank", code: 3102, tpv: "Y" },
    { name: "Janata Sahakari Bank Ltd Pune", code: 3104, tpv: "N" },
    { name: "Kalyan Janata Sahakari Bank", code: 3105, tpv: "N" },
    { name: "Karnataka Bank Ltd", code: 3030, tpv: "Y" },
    { name: "Karnataka Gramin Bank", code: 3113, tpv: "N" },
    { name: "Karnataka Vikas Grameena Bank", code: 3107, tpv: "N" },
    { name: "Karur Vysya Bank", code: 3031, tpv: "Y" },
    { name: "Kotak Mahindra Bank", code: 3032, tpv: "Y" },
    { name: "Maharashtra Gramin Bank", code: 3108, tpv: "N" },
    { name: "Mehsana urban Co-op Bank", code: 3109, tpv: "N" },
    { name: "NKGSB Co-op Bank", code: 3111, tpv: "N" },
    { name: "Nutan Nagarik Sahakari Bank Limited", code: 3112, tpv: "N" },
    { name: "Punjab & Sind Bank", code: 3037, tpv: "Y" },
    { name: "Punjab National Bank - Corporate", code: 3065, tpv: "N" },
    { name: "Punjab National Bank - Retail Banking", code: 3038, tpv: "Y" },
    { name: "RBL Bank", code: 3039, tpv: "Y" },
    { name: "RBL Bank Limited - Corporate", code: 3114, tpv: "N" },
    { name: "Saraswat Bank", code: 3040, tpv: "Y" },
    { name: "SBM Bank India", code: 3115, tpv: "Y" },
    { name: "Shamrao Vithal Bank - Corporate", code: 3075, tpv: "N" },
    { name: "Shamrao Vitthal Co-operative Bank", code: 3041, tpv: "N" },
    { name: "Shivalik Small Finance Bank", code: 3086, tpv: "Y" },
    { name: "South Indian Bank", code: 3042, tpv: "Y" },
    { name: "Standard Chartered Bank", code: 3043, tpv: "Y" },
    { name: "State Bank Of India", code: 3044, tpv: "Y" },
    { name: "State Bank of India - Corporate", code: 3066, tpv: "N" },
    { name: "Suryoday Small Finance Bank", code: 3116, tpv: "N" },
    { name: "Tamil Nadu State Co-operative Bank", code: 3051, tpv: "N" },
    { name: "Tamilnad Mercantile Bank Ltd", code: 3052, tpv: "Y" },
    { name: "Thane Bharat Sahakari Bank Ltd", code: 3118, tpv: "N" },
    { name: "The Kalupur Commercial Co-Operative Bank", code: 3106, tpv: "N" },
    { name: "The Surat Peoples Co-operative Bank Limited", code: 3090, tpv: "Y" },
    { name: "The Sutex Co-op Bank Ltd", code: 3117, tpv: "Y" },
    { name: "TJSB Bank", code: 3119, tpv: "N" },
    { name: "UCO Bank", code: 3054, tpv: "Y" },
    { name: "UCO Bank Corporate", code: 3122, tpv: "N" },
    { name: "Ujjivan Small Finance Bank", code: 3126, tpv: "Y" },
    { name: "Union Bank of India", code: 3055, tpv: "Y" },
    { name: "Union Bank of India - Corporate", code: 3067, tpv: "N" },
    { name: "Utkarsh Small Finance Bank", code: 3089, tpv: "Y" },
    { name: "Varachha Co-operative Bank Limited", code: 3120, tpv: "N" },
    { name: "Yes Bank - Corporate", code: 3077, tpv: "N" },
    { name: "Yes Bank Ltd", code: 3058, tpv: "Y" },
    { name: "Zoroastrian Co-Operative Bank Ltd", code: 3121, tpv: "N" }
];




const walletData = [
    { name: "PayTM", code: 4007 },
    { name: "Amazon Pay", code: 4008 },
    { name: "PhonePe", code: 4009 },
    { name: "Airtel Money", code: 4006 },
    { name: "MobiKwik", code: 4002 },
    { name: "FreeCharge", code: 4001 },
    { name: "Ola Money", code: 4003 },
    { name: "Test Wallet (Sandbox)", code: 4010 }
];
export { netBankingCodes, walletData };